name: trimmer
description: "视频分割widget"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
