name: trimmer_example
description: "Demonstrates how to use the trimmer plugin."

publish_to: "none"

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  trimmer:
    path: ../

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
    # - assets/Butterfly-209.webm
    # - assets/bumble_bee_captions.srt
    # - assets/bumble_bee_captions.vtt
    - assets/Audio.mp3